# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-24 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='details',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
