# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-25 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_auto_20200324_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='details2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='details3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='details4',
            field=models.TextField(blank=True),
        ),
    ]
